### ISSUE TITLE
When installing a custom font in the system, the cursor moves right

### ISSUE THREAD

**Issue by Timofei302** [connectbot/connectbot#1271]
## Bug description

When installing a custom font with an understated width (in my case Ubuntu Normal), in the ConnectBot terminal, the cursor begins to shift to the right, and this offset increases with each printed character.

## Steps to reproduce

1. Go to smartphone Settings
2. Setup custom font
3. Open ConnectBot and connect to SSH server
4. See a problem

## Screenshots

![Screenshot_20230608-081556](https://github.com/connectbot/connectbot/assets/59145732/3220e8a4-fed9-4e7e-8e44-6e5fcf92ae7e)

## Android device

 - Device: Tecno POVA 4 pro
 - OS: Android 12
 - ConnectBot Version: 1.9.9 F-Droid
 - Font: Ubuntu Normal

**Comment by umoenks** [comment]
The shift happens here even with Standard font.
Device: Samsung Galaxy S22
OS: Android 13
Font: Standard

**Comment by Timofei302** [comment]
> Сдвиг здесь происходит даже со стандартным шрифтом. Очень сложно найти правильное место при попытке исправить опечатку...
> 
> Устройство: Samsung Galaxy S22 Версия ConnectBot: 1.99-oss (F-Droid) ОС: Андроид 13 Шрифт: стандартный

Hmm... Well, I have no problems with the standard font, either on my main phone or on my previous one (Samsung Galaxy A30s, Android 11).

![Screenshot_20230610-091430](https://github.com/connectbot/connectbot/assets/59145732/a35738d7-fd59-42d1-8a89-8bd62886c0ae)

**Comment by Timofei302** [comment]
> The shift happens here even with Standard font. Makes it reeeeaaaally hard to find the right spot when trying to fix a typo...
> 
> Device: Samsung Galaxy S22 ConnectBot version: 1.99-oss (F-Droid) OS: Android 13 Font: Standard

Hmm... Well, I have no problems with the standard font, either on my main phone or on my previous one (Samsung Galaxy A30s, Android 11).
![Screenshot_20230610-091430](https://github.com/connectbot/connectbot/assets/59145732/310fa71b-8db0-4d2d-920b-d32a1b62ddff)

**Comment by DrDecagon** [comment]
I also have this issue with the standard font on both phones I use.
ConnectBot 1.9.9-oss
Android 12

**Comment by kunert7062** [comment]
All I did was select a 2 point larger font. Ever since, it's messed up as in OP's case, between 5-10 spaces between the cursor and the text.  Did a complete uninstall and reinstall (deleting all used storage space and having to setup my connections again), and it's still messed up. I can't even find any way to change fonts, but no size helps, it's always there.

About to switch to Juice it's so annoying. Every other device is fine, just my main.

**Comment by kastaneda** [comment]
Same font issue on Samsung S22+. Anyone have an idea how to fix it?

**Comment by kastaneda** [comment]
![Screenshot_20231008_135703_ConnectBot](https://github.com/connectbot/connectbot/assets/773051/52b90a47-46a8-4c8a-8686-40fc01273c35)
That's screwed Midnight Commander. Note that width of bold font is OK.

**Comment by kastaneda** [comment]
Seems that's Samsung problem. I had SamsungOne font installed as a default system font; when I reverted the font setting to the 'standard' one, ConnectBot rendering becomes way better.

**Comment by Jilas** [comment]
Just experiencing this on a Moto G62 5g using stock font since upgrading to Android 13 (Android 12 was fine from what I can remember).

If there is any info you need or Ideas to fix this let me know.

Thanks.

**Comment by demetera** [comment]
I have the same with my Moto g72 with the stock Android 12 and I didn't find any solution how to fix the issue.

In official handbook from Motorola there is a statement that you can set up your own font style, but I'm unable to find this option on my phone.

**Comment by Jilas** [comment]
I finally found the setting in Android 13.  Tap and hold the screen, to bring up the widgets, and use the personalise option, and change it to a different font (in Android 11 it's in the settings, display, styles section).

I can live with a stock android font as it makes this look right.

Hope this helps the others that got stuck looking for this setting.

**Comment by ToniCipriani** [comment]
Same issue with the Motorola ThinkPhone, when using the "Square" Font.

**Comment by srvr-au** [comment]
Fixed issue on moto g54 by making font bold. Changing font didn't help

**Comment by ekalin** [comment]
I also had this sproblem when using a non-standard font. I suppose an option to select a font for the terminal would solve this problem.

**Comment by hydrian** [comment]
This seems to related to a changes in android 12 and Material Design. Some phone's settings let you change font size and color but not actual font. My Moto G Stylus 5G 2023 is an example of this which came stock with Android 13. Screenshot attached. ![Screenshot_20240204-222232.png](https://github.com/connectbot/connectbot/assets/988950/8b7dd517-d703-407b-9818-9b23ae9f3965)


I recommend adding the feature to set the font in-app. This will help fix the issues across multiple manufacturers.

**Comment by hydrian** [comment]
> I finally found the setting in Android 13.  Tap and hold the screen, to bring up the widgets, and use the personalise option, and change it to a different font (in Android 11 it's in the settings, display, styles section).
> 
> I can live with a stock android font as it makes this look right.
> 
> Hope this helps the others that got stuck looking for this setting.

My Moto G Stylus 5G 2023 (Android 13) doesn't have the personalize widget.

**Comment by hydrian** [comment]
> Fixed issue on moto g54 by making font bold. Changing font didn't help 

Enabling bold in system settings didn't fix my font probm on my Moto G Stylus 5G 2023.

**Comment by bttrx** [comment]
> Fixed issue on moto g54 by making font bold. Changing font didn't help

Didn't work for my Moto G55 5G (Android 15).
But changing the system font from „Default“ to „Android“ fixed it. (#1381)

**Comment by nindanaoto** [comment]
This seems to be a font related issue so we can close this now since we have a custom font support in the beta.
